source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'IJKPlayerFrameworkSSL_Example' do
  pod 'IJKPlayerFrameworkSSL', :path => '../'

  target 'IJKPlayerFrameworkSSL_Tests' do
    inherit! :search_paths

    
  end
end
